server:
  port: 9001
spring:
  application:
    name: business-core-portal
  webflux:
    base-path: /utp-portal/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:${DB_PORT}/db_utp_portal
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi/bs-utp-portal-v1.yaml